## device: 1 v100-32G
## data
data_file: dataset/electricity.csv
num_channels: 321
seq_len: 336
label_len: 96
stride: 48
patch_len: 96

## model
model: gridtst
num_layers: 3
d_model: 256
ffn_dim: 256
dropout: 0.2
attention_dropout: 0.2
revin_affine: false
norm_type: batchnorm
attention_strategy: channel_first

## training
per_device_train_batch_size: 64
per_device_eval_batch_size: 64
adam_eps: 1.0e-8
weight_decay: 0.0005
max_grad_norm: 1.0
lr: 0.0001
max_train_epochs: 100
seed: 19980406
gradient_accumulation_steps: 1
val_check_interval: 1.0
pct_start: 0.12
fp16: false
torch_compile: false

